# Generated by Django 3.2.12 on 2022-04-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_rename_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
