# Generated by Django 3.2.12 on 2022-04-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_categories_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='optional_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
