# Generated by Django 3.2.12 on 2022-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='stock',
            field=models.IntegerField(default=10),
        ),
    ]
